package top.imlk.ncee;

import top.imlk.ncee.verify.CrackResult;

import javax.swing.*;
import java.awt.*;

public class OpenCVForm {
    public JSlider slider1;
    public JPanel rootPanel;
    public JLabel srcImgLabel;
    public JLabel smallImgLabel;
    public JLabel resultImgLabel;
    public JButton exitButton;
    public JFrame openCVFrame;

    public static void main(String[] args) {
        new OpenCVForm().show();
    }

    public void show() {

        openCVFrame = new JFrame("OpenCVForm");
        openCVFrame.setLocation(777, 377);
        openCVFrame.setContentPane(this.rootPanel);
        openCVFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        openCVFrame.pack();
        openCVFrame.setVisible(true);

        this.exitButton.addActionListener((event) -> {
            openCVFrame.setVisible(false);
            openCVFrame.dispose();
        });
    }

    public void showCreckResult(CrackResult crackResult) {

        srcImgLabel.setIcon(new ImageIcon(crackResult.crackedNormalImg));
        smallImgLabel.setIcon(new ImageIcon(crackResult.crackedSmallImg));
        resultImgLabel.setIcon(new ImageIcon(crackResult.crackedResultImg));

    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridBagLayout());
        rootPanel.setAlignmentX(0.0f);
        rootPanel.setAlignmentY(0.0f);
        rootPanel.setAutoscrolls(false);
        rootPanel.setDoubleBuffered(true);
        rootPanel.setFocusable(false);
        rootPanel.setMinimumSize(new Dimension(0, 0));
        rootPanel.setOpaque(true);
        rootPanel.setPreferredSize(new Dimension(888, 555));
        rootPanel.setVisible(true);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 400;
        gbc.ipady = 200;
        rootPanel.add(panel1, gbc);
        srcImgLabel = new JLabel();
        srcImgLabel.setHorizontalAlignment(0);
        srcImgLabel.setHorizontalTextPosition(0);
        srcImgLabel.setText("source");
        srcImgLabel.setVerticalAlignment(3);
        srcImgLabel.setVerticalTextPosition(3);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        panel1.add(srcImgLabel, gbc);
        smallImgLabel = new JLabel();
        smallImgLabel.setHorizontalAlignment(0);
        smallImgLabel.setHorizontalTextPosition(0);
        smallImgLabel.setText("small");
        smallImgLabel.setVerticalAlignment(3);
        smallImgLabel.setVerticalTextPosition(3);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        panel1.add(smallImgLabel, gbc);
        resultImgLabel = new JLabel();
        resultImgLabel.setHorizontalAlignment(0);
        resultImgLabel.setHorizontalTextPosition(0);
        resultImgLabel.setText("result");
        resultImgLabel.setVerticalAlignment(3);
        resultImgLabel.setVerticalTextPosition(3);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        panel1.add(resultImgLabel, gbc);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        rootPanel.add(panel2, gbc);
        slider1 = new JSlider();
        slider1.setMaximum(5);
        slider1.setPreferredSize(new Dimension(400, 22));
        slider1.setValue(0);
        panel2.add(slider1);
        exitButton = new JButton();
        exitButton.setText("Exit");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rootPanel.add(exitButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
